parameters:
#    piorun_hello.example.class: Piorun\HelloBundle\Example

services:
#    piorun_hello.example:
#        class: %piorun_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
