# app/config/routing.yml
my_hello_world:
    resource: "@MyHelloWorldBundle/Controller/"
    type:     annotation
    prefix:   /

piorun_hello:
    resource: "@PiorunHelloBundle/Resources/config/routing.yml"
    prefix:   /

piorun_home_site:
    resource: "@PiorunHomeSiteBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
